#!/usr/bin/env sh

# Load scripting addition
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# Configure layout
yabai -m config layout               bsp
yabai -m config window_gap           8
yabai -m config top_padding          4
yabai -m config bottom_padding       4
yabai -m config left_padding         4
yabai -m config right_padding        4

# Configure mouse support
yabai -m config mouse_modifier       alt
yabai -m config mouse_action1        move
yabai -m config mouse_action2        resize

# Configure focus and behavior
yabai -m config focus_follows_mouse  off
yabai -m config mouse_follows_focus  off
yabai -m config window_placement     second_child
