# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

toggle: BACKSPACE

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Phrases
  - trigger: ":imo"
    replace: "in my opinion"

  - trigger: ":asap"
    replace: "as soon as possible"

  - trigger: ":btw"
    replace: "by the way"

  - trigger: ":fwis"
    replace: "from what I see"

  - trigger: ":ofc"
    replace: "of course"

  # Words
  - trigger: ":def"
    replace: "definitely"

  # Code
  - trigger: ":mdc"
    replace: "```\n\n```"

  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"

  # Personal info 
  - trigger: ":name"
    replace: "Nikita"

  - trigger: ":sname"
    replace: "Tchayka"

  - trigger: ":fsname"
    replace: "Tchayka Razumov"

  - trigger: ":fname"
    replace: "Nikita Tchayka Razumov"

  - trigger: ":email"
    replace: "nikitatchayka@gmail.com"

  - trigger: ":wemail"
    replace: "nick@theagilemonkeys.com"

  - trigger: ":address"
    replace: "Calle Tamara 13"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  - trigger: ":shrug"
    replace: "¯\\_(ツ)_/¯"
